trigger: none  # CD should only run after CI completes

pr: none

resources:
  pipelines:
    - pipeline: buildPipeline   # name to reference
      source: Docosoft-CI-Pipeline  # name of the CI pipeline in Azure DevOps
      trigger: true  # automatically triggers this CD pipeline after CI completes

pool:
  name: Default  # Your self-hosted agent pool

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download CI artifact'
      inputs:
        artifact: 'drop'      # This must match CI pipeline's ArtifactName
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: 'AzureServiceConnection'  # ✅ Your Azure connection name
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'                # ✅ Your Azure Web App name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'  # ✅ Path to your zip file
