trigger: none  # Disable commit-based trigger

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Docosoft-CI-Pipeline  # Use the exact name of your CI pipeline
      trigger: true

pool:
  name: Default  # Your self-hosted agent pool

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download build artifact'
    inputs:
      artifact: drop
      path: $(Pipeline.Workspace)

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure App Service'
    inputs:
      azureSubscription: 'AzureServiceConnection'  # Your service connection name
      appType: 'webAppLinux'
      appName: 'Murugu-docoweapp'  # Your App Service name
      package: '$(Pipeline.Workspace)/drop/**/*.zip'
