trigger: none  # Because this is CD

pr: none

pool:
  name: Default

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnection'  # replace with your real service connection name
    appType: 'webApp'
    appName: 'Murugu-docowebapp'
    package: '$(System.ArtifactsDirectory)/drop'
