trigger: none  # manual or CI-triggered

pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Murugucse.Docosoft
      trigger:
        branches:
          include:
            - main

pool:
  name: Default # use your self-hosted agent pool

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download build artifact'
      inputs:
        artifact: drop
        path: $(Pipeline.Workspace)

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: 'AzureServiceConnection' # update this to your actual service connection name
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp' # update this to your Azure App Service name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
