trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Docosoft-CI-Pipeline
      trigger: true

pool:
  name: Default

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        artifact: 'drop'
        path: '$(Pipeline.Workspace)/drop'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'  # 🔁 Update to match your service connection
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'
        package: '$(Pipeline.Workspace)/drop/*.zip'
