trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Docosoft-CI-Pipeline  # ✅ exact name of your CI pipeline
      trigger: true

pool:
  name: Default

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download CI artifact'
      inputs:
        source: current
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: 'AzureServiceConnection'  # ✅ replace with your service connection name
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'  # ✅ replace with your Azure Web App name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
