trigger:
  branches:
    include:
      - main  # or your release branch

pool:
  name: Default  # Your self-hosted agent name

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnection'  # 👈 service connection name from step 1
    appType: 'webAppLinux'
    appName: 'Murugu-docowebapp'
    package: '$(System.DefaultWorkingDirectory)/_yourartifactpath/drop.zip'
