trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Your self-hosted agent pool name

jobs:
- job: BuildAndTest
  displayName: 'CI - Build and Test'
  steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        version: '8.0.100'  # 🔁 Use an exact valid version, 8.0.x is invalid

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
