trigger: none  # CD runs only after CI pipeline

pr: none

resources:
  pipelines:
    - pipeline: buildPipeline  # This is a reference name
      source: Docosoft-CI-Pipeline  # Name of your CI pipeline exactly
      trigger: true  # CD auto-triggers after CI succeeds

pool:
  name: Default

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'  # ✅ FIX: Get the artifact from the CI build that triggered this CD
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
