trigger: none  # CD runs only when triggered from CI

resources:
  pipelines:
    - pipeline: buildPipeline  # alias
      source: Docosoft-CI-Pipeline
      trigger: true

pool:
  name: Default  # Or use: vmImage: 'ubuntu-latest'

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
