trigger: none  # Manual or pipeline-triggered only

pr: none

resources:
  pipelines:
    - pipeline: buildPipeline  # reference name used in this file
      source: Docosoft-CI-Pipeline  # name of your CI pipeline
      trigger: true  # triggers CD when CI completes

pool:
  name: Default

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'Docosoft'
        pipeline: $(resources.pipeline.buildPipeline.pipelineID)
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'  # ✅ Your service connection name
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'  # ✅ Your app name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
