# azure-release.yml
trigger:
  branches:
    include:
      - main

# Only run when the build artifact is available
pr: none

stages:
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    pool:
      name: Default   # Your self-hosted agent pool name

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: drop
        path: $(Pipeline.Workspace)

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'  # Use your service connection name
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'                # Your App Service name
        package: '$(Pipeline.Workspace)/drop/drop.zip'  # Adjust if your artifact path is different
