trigger: none  # CD pipeline is triggered by CI pipeline

pr: none

resources:
  pipelines:
    - pipeline: buildPipeline  # reference name used below
      source: Docosoft-CI-Pipeline  # ✅ Must match CI pipeline name
      trigger: true  # 🔁 Auto-trigger CD after CI succeeds

pool:
  name: Default

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'  # ✅ Use 'current' for latest run
        artifact: 'drop'
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'  # ✅ Must match your service connection
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'  # ✅ Must match Azure App name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
