trigger: none  # prevent triggering on source changes

resources:
  pipelines:
    - pipeline: CITrigger
      source: Docosoft-CI-Pipeline  # ✅ Replace with your CI pipeline name exactly
      trigger: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Deploy
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - checkout: self

    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'pipeline'
        artifact: 'drop'
        path: '$(Pipeline.Workspace)/drop'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'  # ✅ Replace with your service connection
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'                # ✅ Replace with your app name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
