trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Docosoft-CI-Pipeline
      trigger: true

pool:
  name: Default

jobs:
- job: DeployJob
  displayName: 'CD - Deploy to Azure Web App'
  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'   # ✅ use 'current' to get artifact from triggering build
        artifact: 'drop'       # ✅ must match what was published in CI
        path: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection'
        appType: 'webAppLinux'
        appName: 'Murugu-docowebapp'
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
